QA-14958: Fix saml callback not working if url has parameters
Jahia/saml-authentication-valve pull request #82
Opened 2023-09-06 14:01 UTC by jahia-carp

https://jira.jahia.org/browse/QA-14958

2023-09-06 14:18 UTC, jkevan requested changes

2023-09-06 14:18 UTC, jkevan commented on src/main/java/org/jahia/modules/saml2/actions/SAMLCallback.java
> +        assert redirection != null;
What is the purpose of this assertion ?
There is already checks in previous lines, that will anyway set a default `redirection` to "/".
So it's likely impossible for `redirection` to be null at that place.

2023-09-06 14:24 UTC, jsinovassin commented on src/main/java/org/jahia/modules/saml2/actions/SAMLCallback.java
> +        assert redirection != null;
Why do we need this assert, redirection will  be at least equals to "/", have a look to the line 108

2023-09-07 05:03 UTC, jahia-carp commented on src/main/java/org/jahia/modules/saml2/actions/SAMLCallback.java
> +        assert redirection != null;
Yes fixed, sorry about that, it was to please my code editor a bit too quickly ;-)

2023-09-07 05:03 UTC, jahia-carp commented on src/main/java/org/jahia/modules/saml2/actions/SAMLCallback.java
> +        assert redirection != null;
thanks, fixed

2023-09-07 07:34 UTC, jkevan approved these changes

2023-09-07 07:49 UTC, merged